sudo: false
language: node_js
addons:
  sauce_connect: true
cache:
  directories:
    - $HOME/.npm
node_js:
  - 6 # to be removed 2019-04-01
  - 8 # to be removed 2019-12-31
  - 10 # to be removed 2021-04-30
  - 11 # to be removed 2019-06-30
  - lts/* # safety net; don't remove
  - node # safety net; don't remove
before_install:
  - npm i -g npm
script:
  - npm t
after_success:
  - 'travis-after-all && npm run semantic-release'
env:
  global:
    - SAUCE_CONNECT_READY_FILE=/tmp/sauce-connect-ready
    - LOGS_DIR=/tmp/chai-build/logs
    - secure: Xrfl4VzQ3C/06kC+KMNMNRxnbJBOamuRnHj+/E8vbQYVNvokvV13Q4P4bMlk+j8ZvR0YUCnM0cUjQPpvEd5W0wHTSj0K1gpUh8EyzH8KI8sOWYX6P4HQQf7N2niqI1zECn0hqi2jsinem3tMtHgB5yTrrwqmob61Nmj2cc+/Am/maR3pF3/Ob9pfBBNZoMPmxWiSLk9lsiMaStFQfODuJU3lrMBlbZivQZ5KEAHYhGPXf9mSrzRO28tX53ZuEZjstoRhNd1hKcO+eUosWcAgSjYGW92n9jGA0ht9bAFnEcHaHRwFGZod5BrfcDBcEYTVHwEBI5z1n+u1enFA25QYw7ORDFg1L4aszw2hGEM0iilM2fv+t086aff+HcFM6ozXYviO05Vuw9oja2Iwu4rblP7xwjFd/LSDUklEeKxXbPAee1HTc1+iZ1LCPO5bgNJqHscrkRb4xL5fq+LBL1oEHBybQcxAkkIjKAEkbrGVahFkNrzySnoHgEgd2XVhPqDq2M8L2lDEfNaNGoN7MrCRbbu8/pLzMGfSXAqWveVx+hksZnryxt4htUZpwuykjm/L6TPppfdzU5A2yH5iusZb7pkgaqe8NJgnGBHq4wagfMxBe8IaAhnPigd6WLu75S68EeoSTXDOMFp6BN4dWv9Ya1oQ+L2e9w8sZQ/2SMw+4gk=
    - secure: NmCIZ3bBmfg35rD+xY7bbuI9rtVyoZNGvzC5uJW2wzaJlPWURHyLJHJ13QhtXcptLLtseJY6PH6nK+JIjNSoDPK4Wsoxv2Ozp2rq/lFhKDS2umujM6YDPSUlSChdlP1hRio317YzSciXOFtu1WIzKiv0QBtxREnV1V91a5fUyayh9mNM4/VrEFoNQKmYstMJsDuUrE0TPyet4v81ejw5xP2wX3CJuqu/eb5hJezFS2rlhzT8i8RNjb97+lSjNzyR2z3FwLDtrUj8SaWQ07HxJSHRRf41+q7czx0FAQlBF1+EKJ2tf45l/PaHPBCSHSdUoIHoOCSGLEH0JL9H9bxBWwuzM78eywsnVAVVnsokso7t96/2PdKqULWUp9f9eiiWz3vCz5lRqPXVO8If3KemQVtmhVZwssjM43SqloW6HS3PAhSFpypx1Oz25XTpx/u7v641P/Hc+hH++GF/wJ7LR0c417hQrK2dZNG2067WUKM/xyaU3KYPal95LxObqJnhLDsU4zmIpliK0VkaUnYEMFXErE+GPVxcp1FCH6ZO2nnTbd1QKVWg/6unGyOePo3y4fK3ZuygxrEuEwU1RIhruf2+1xlNDMpyTjY65V7g3rpk4OAlfx+5lM3Ws6IXXTkgTMTNFjqDR/53Nv3dJgFYfmXV/SQ1A4vk1I4XufN3s+s=
    - secure: tjY+Qd/Z/C/n2qkvYg05utkZgtn/o4AcjmP/Pco5ZsuR2/PP7rs0Jz+fnF1YixNVkatAub52/rQ0LyIqTkEqcOq9fjfzRwwDMwW/Cb0lakdZTqYoIp0E5WCNIlQi6uBfk1tPxG9x4edqLHE+GWjNrxdiWTPNEe6jfObRpPa6uV/ewTzYomvtwqPZkoDfAG3zXP87APK43CFtFNwmHc+Apf6D6dfPy+0vgwLYpRmPeB8RsabpV0sWAzy2A0RK+UGIrO6Bx8Yupi4Si6lGuW6Lk5r8TtdGk3gnt9C8zMS+w8UvCQ7gOBKkyQI9bI3t3pAFcEWsL7mbQq2axEdhJJdKS20190ps6ImTxyc1kOPnt5JcAXN72etx7cDhMDw3FtHtBboGydRd0lBpuAgq8gKl9X/CiPfghv1hea8HB2YADEvFmvX5dZ/XxBNg6aI8yhnn7hNM+9gXtVrW0C1D43TbQXE7TqNLCvRlQkamQJH+32rqu6dAPoBtwZF2kZLSfJR+xAr9HJjEtXW9nD3OTfjlQpvJZNwM5yLEw9mob1ukTPadBW3irTYDAyBke0aT66gX4a80EOcptPZExDBz9DFGWoW48wf+VZvrFwaOcNXNp3244epaZUZ68wC4/kWH/21ky8m09+IGI284q3QfGea1drjwZFB/EX1zvY2LXOwB8go=
    - secure: V7dv1sEDKU9RPAgaJjk7E2PUarMSzf18GVNGmS6LrNZ5HH88Lv8XEpJj2fnvmJNFgqxnjDiXlQC/EfzbsrR+hI+i2gDv3Yti3Uqs02fkfWuZ+g9YEfuGBEW2Iv+L2+klG4OQsKa32HQZvvJWSrPB+DjK5QsAoVkaiovgMzsUXY67IXJ9/OORy+M8dIHjkEL1pq27eD/R9cKK8fxC1Ld7GsJHyNlbj7CN+vuYnPe7WsFwdoI9X5PD4Qrq2w3nzNa13Fp04dD9chjScUHPeoIYl0P0SRm4ySuw5lrvONQ2EHVXjuNdHUeoByebAPcFPbO7XhMSdmsJFF17ejLuRKNPvzLVeLa2LwzQl+e6OizRQe2oxHDtU6MQZP58pq4G50GO9jAjIsEtraY19DX+gMx3YJSt7rB8B0AwrH2efLEJDU8D5lcRpj56e8VZr4PSWpdk8pVMOg6Qi6Qn/PyBJ4U2JkSSME/bResQlZSl3+jdj1Tk1mWHWUHltyU5xoDZ1cOyRfymOlgy9g3dB5xmf773cKQbMqUderZBO/SXhuzMkm6l6pfBFTPBLKlE+SNFa6K+k9cpKRlxhVHcxIy7i6DsOkxIW36Kg/kmMsGIrsGTTt7RvdHt8N7OuG8AP4+EkBEkyObpvY6V27D6QeFNyrASYkVH7V0q4+uJXX6ISkd4E7s=
